api/urls.py
from django.conf.urls import url
from . import views


app_name = 'api'
urlpatterns = [
    url(r'^comment/(?P<post_id>\d+)/?$', views.CommentView.as_view(),
        name='api-comment'),
    url(r'^(post/)?(?P<post_id>\d+)/?$', views.PostView.as_view(),
        name='api-post'),
    url(r'^archive/((?P<post_id>\d+)/)?((counts/)(?P<number>\d+)/)?$',
        views.ArchiveView.as_view(), name='api-archive'),
]

backstage/urls.py
from django.conf.urls import url
from . import views


app_name = 'backstage'
urlpatterns = [
    url(r'^data/import/?$', views.DataImportView.as_view(),
        name='import-data'),
    url(r'^data/export/?$', views.DataExportView.as_view(),
        name='export-data'),
    url(r'^data/?$', views.index, name='data'),
]

inside/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mblog.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^manage/', include('backstage.urls')),
]

backstage/views.py
import datetime
import json
import tempfile
from operator import itemgetter
from django.http import FileResponse, Http404
from django.shortcuts import render
from django.views import View
from mblog.models import Post, Comment


class DataImportView(View):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        content = {
            "success": False,
            "message": "Import the posts"
        }
        return render(request, "mblog/data-upload-result.html", content)

    def parse_request_data(self, request):
        data_file = request.FILES.get("data", None)
        if not data_file:
            raise ValueError("Please Select data file.")

        data_str = data_file.read()
        try:
            posts = json.loads(data_str.decode())["posts"]
        except ValueError:
            raise ValueError("JSON parsing error")
        return posts

    def post(self, request):
        content = {
            "success": True
        }
        try:
            posts = self.parse_request_data(request)
        except ValueError as e:
            content.update({
                "success": False,
                "message": e.args[0]
            })

        if content["success"]:
            posts.sort(key=itemgetter("pub_date"))
            for p in posts:
                pub_date = datetime.datetime.fromtimestamp(p["pub_date"])
                post = Post.objects.create(
                    content=p["content"], pub_date=pub_date, exist=p["exist"])

                for c in p["comments"]:
                    comment = Comment(post=post, author=c["author"],
                                      content=c["content"])
                    comment.save()
            content["success"] = True
            content["message"] = "%d posts has been imported!" % len(posts)
        return render(request, "backstage/data-upload-result.html", content)


class DataExportView(View):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise Http404
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        data = {}
        data["posts"] = [post.dump_payload for post in Post.objects.all()]
        json_data = json.dumps(data)
        f = tempfile.SpooledTemporaryFile(mode="wb")
        f.write(json_data.encode('utf-8'))
        f.seek(0)

        response = FileResponse(f)
        response["Content-Type"] = "application/octet-stream"
        response["Content-Disposition"] = ('attachment; filename='
                                           '\"inside-data.json\"')
        return response


def index(request):
    if not request.user.is_superuser:
        raise Http404

    return render(request, "backstage/data.html")

backstage/templates/backstage/data-upload-result.html
{% extends "base.html" %}

{% block title %}Upload{% endblock %}

{% block content %}
<div id="content_bg">
	<h1>{{ message }}</h1>
	{% if not success %}
		<form enctype="multipart/form-data" action="{% url "backstage:import-data" %}" method="post">
			{% csrf_token %}
			<!-- <p><textarea name="content" rows="5" cols="20"></textarea></p> -->
			<input type="file" name="data" />
			<input type="submit" value="导入"></input>
		</form>
	{% else %}
		<p>3 秒后将跳转到归档页面</p>
	{% endif %}
</div>
{% if success %}
<script>
	setTimeout(function () {
		location.href = "/archive";
	}, 3000);
</script>
{% endif %}
{% endblock %}

backstage/templates/backstage/data.html
{% extends "base.html" %}

{% block title %}Data{% endblock %}

{% block content %}
<div id="content_bg">
	<h1>Data Operation</h1>
	<form enctype="multipart/form-data" action="{% url 'backstage:import-data' %}" method="post">
		{% csrf_token %}
		<!-- <p><textarea name="content" rows="5" cols="20"></textarea></p> -->
		<input type="file" name="data" />
		<input type="submit" value="导入"></input>
	</form>
	<a href="{% url 'backstage:export-data' %}"><button>导出</button></a>
</div>
{% endblock %}