api/urls.py
from django.conf.urls import url
from . import views


app_name = 'api'
urlpatterns = [
    url(r'^comment/(?P<post_id>\d+)/?$', views.CommentView.as_view(),
        name='api-comment'),
    url(r'^(post/)?(?P<post_id>\d+)/?$', views.PostView.as_view(),
        name='api-post'),
    url(r'^archive/((?P<post_id>\d+)/)?((counts/)(?P<number>\d+)/)?$',
        views.ArchiveView.as_view(), name='api-archive'),
]

backstage/urls.py
from django.conf.urls import url
from . import views


app_name = 'backstage'
urlpatterns = [
    url(r'^data/import/?$', views.DataImportView.as_view(),
        name='import-data'),
    url(r'^data/export/?$', views.DataExportView.as_view(),
        name='export-data'),
    url(r'^data/?$', views.index, name='data'),
]

inside/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mblog.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^manage/', include('backstage.urls')),
]

mblog/urls.py
from django.conf.urls import url
from . import views
from . import auth


app_name = 'mblog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^0$', views.add_post, name='add'),
    url(r'^login/?$', auth.user_login, name='login'),
    url(r'^logout/?$', auth.user_logout, name='logout'),
    url(r'^archive/?$', views.archive, name='archive'),
    url(r'^(?P<pk>\d+)$', views.view_post, name='post'),
]

mblog/models.py
# coding: utf-8
import time
from django.db import models


class Post(models.Model):
    content = models.TextField("Content")
    pub_date = models.DateTimeField("Date Published", auto_now_add=True)
    exist = models.BooleanField(default=True)

    @property
    def abstract(self):
        content = self.content
        if len(content) > 15:
            return content[:15]+"..."
        else:
            return content

    def __str__(self):
        return self.abstract

    def get_obj(self):
        return {
            "content": self.content,
            "pub_date": self.time_str
        }

    @property
    def time_str(self):
        return self.pub_date.strftime("%Y-%m-%d %H:%M:%S")

    def serialize(self):
        result = {
            "id": self.id,
            "content": self.content,
            "pub_date": self.time_str,
            "comments": []
        }
        for comment in self.comment_set.all():
            result["comments"].append(comment.serialize())

        return result

    @property
    def dump_payload(self):
        result = {
            "id": self.id,
            "content": self.content,
            "pub_date": int(time.mktime(self.pub_date.timetuple())),
            "exist": self.exist,
            "comments": []
        }
        for comment in self.comment_set.all():
            result["comments"].append(comment.serialize())

        return result


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    author = models.CharField(max_length=32)

    @property
    def abstract(self):
        content = self.content
        if len(content) > 15:
            return content[:15] + "..."
        else:
            return content

    def __str__(self):
        return self.abstract

    def serialize(self):
        return {
            "content": self.content,
            "author": self.author,
        }

mblog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from mblog.models import Post
from mblog.utils import serve_static


@login_required
def index(request):
    post = Post.objects.filter(exist=True).order_by("pk").last()
    if post:
        return HttpResponseRedirect(
            reverse('mblog:post', kwargs={"pk": post.id}))
    else:
        raise Http404


@login_required
def view_post(request, pk):
    if request.user.has_perm("mblog.change_post"):
        post = get_object_or_404(Post, pk=pk)

        previous_post = Post.objects.filter(pk__lt=pk).order_by("-pk").first()
        previous_post_id = previous_post.id if previous_post else 0
        next_post = Post.objects.filter(pk__gt=pk).first()
        next_post_id = next_post.id if next_post else 0

        context = {
            "post": post,
            "previous": previous_post_id,
            "next": next_post_id
        }
        return render(request, "mblog/edit.html", context)
    else:
        return serve_static("mblog/static/mblog/html/post.html")


@login_required
def archive(request):
    return serve_static("mblog/static/mblog/html/archive.html")


@login_required
def add_post(request):
    if request.method == "GET":
        return render(request, "mblog/new.html")
    elif request.method == "POST":
        post = Post(content=request.POST["content"])
        post.save()
        return HttpResponseRedirect(
            reverse('mblog:post', kwargs={"pk": post.id}))

mblog/templates/mblog/data-upload-result.html
{% extends "mblog/base.html" %}

{% block title %}Upload{% endblock %}

{% block content %}
<div id="content_bg">
	<h1>{{ message }}</h1>
	{% if not success %}
		<form enctype="multipart/form-data" action="{% url "mblog:import-data" %}" method="post">
			{% csrf_token %}
			<!-- <p><textarea name="content" rows="5" cols="20"></textarea></p> -->
			<input type="file" name="data" />
			<input type="submit" value="导入"></input>
		</form>
	{% else %}
		<p>3 秒后将跳转到归档页面</p>
	{% endif %}
</div>
{% if success %}
<script>
	setTimeout(function () {
		location.href = "/archive";
	}, 3000);
</script>
{% endif %}
{% endblock %}

mblog/templates/mblog/data.html
{% extends "mblog/base.html" %}

{% block title %}Data{% endblock %}

{% block content %}
<div id="content_bg">
	<h1>Data Operation</h1>
	<form enctype="multipart/form-data" action="{% url "mblog:import-data" %}" method="post">
		{% csrf_token %}
		<!-- <p><textarea name="content" rows="5" cols="20"></textarea></p> -->
		<input type="file" name="data" />
		<input type="submit" value="导入"></input>
	</form>
	<a href="/data/inside-data.json"><button>导出</button></a>
</div>
{% endblock %}

mblog/templates/mblog/edit.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Inside{% endblock %}

{% block library %}
{% endblock %}

{% block content %}
<div id="content_bg" post-id="{{ post.id }}">
	<div class="row">
		<div class="col v2 center">	
			<div id="form">
				{% csrf_token %}
				<p><textarea name="content" rows="5" cols="20">{{ post.content }}</textarea></p>
				<p><input type="checkbox" name="exist" {% if post.exist %}checked="checked"{% endif %}>Exist</input></p>
				<button id="update">更改</button>
				<button id="delete">删除</button>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col v2 right time">
			<p>{{ post.time_str }}</p>
		</div>
	</div>
	<div class="row">
		<div class="col v2">
			<h3>Comments</h3>
			{% for comment in post.comment_set.all %}
				<p>{{ comment.author }}：{{ comment.content }}</p>
			{% endfor %}
			<div id="comment" class="center" method="post">
				{% csrf_token %}
				<p>
					<label for="comment_nickname" class="form-l" for="author">昵称：</label>
					<input type="text" class="form-r" name="author" />
				</p>
				<p>
					<label for="comment_nickname" class="form-l" for="content">内容：</label>
					<input type="text" class="form-r" name="content" />
				</p>
				<p>
					<button type="submit" value="评论">评论</button>
				</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col v2 center">
			<div class="col {% if not previous %}disabled{% endif %}">
				<a href="{% url 'mblog:post' previous %}" class="link">上一篇</a>
			</div>
			<div class="col {% if not next %}disabled{% endif %}">
				<a href="{% url 'mblog:post' next %}" class="link">下一篇</a>
			</div>
		</div>
	</div>		
</div>
<script type="text/javascript" src="{% static "mblog/js/edit.min.js" %}"></script>
{% endblock %}

mblog/templates/mblog/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Login{% endblock %}

{% block content %}
<div id="content_bg">
	<div class="row">
		<div class="col v2 center">
			<h1>Login</h1>
			{% if not request.user.is_authenticated %}
				{% if error %}
				<div class="error">
					{{ error }}
				</div>
				{% endif %}
				<form action="{{ request.get_full_path }}" method="post">
					{% csrf_token %}
					<p>Username: <input type="text" name="username" /></p>
					<p>Password: <input type="password" name="password" /></p>
					<input type="submit" value="login" />
				</form>
			{% else %}
				<p>You're logged in as {{ request.user.username }}~</p>
				<button>
					<a href="{% url 'mblog:logout' %}">Log out</a>
				</button>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

mblog/templates/mblog/manage.html
{% extends "mblog/base.html" %}

{% block title %}Manage{% endblock %}

{% block content %}
<div id="content_bg">
	<h1>Manage!</h1>
	<form action="{% url "mblog:manage" %}" method="post">
		{% csrf_token %}
		<p><textarea name="content" rows="5" cols="20"></textarea></p>
		<input type="submit" value="提交"></input>
	</form>
</div>
{% endblock %}

mblog/templates/mblog/new.html
{% extends "base.html" %}

{% block title %}Add a Post{% endblock %}

{% block content %}
<div id="content_bg">
	<h1>New</h1>
	<form action="{% url "mblog:add" %}" method="post">
		{% csrf_token %}
		<p><textarea name="content" rows="5" cols="20"></textarea></p>
		<input type="submit" value="提交"></input>
	</form>
</div>
{% endblock %}

mblog/templates/mblog/post.html
{% extends "mblog/base.html" %}
{% load staticfiles %}

{% block title %}Inside{% endblock %}

{% block library %}
	<script src="//cdn.bootcss.com/jquery/2.2.1/jquery.min.js"></script>
{% endblock %}

{% block content %}
<div id="content_bg" post-id="{{ post.id }}">
	<div class="row">
		<div class="col v2 center">	
			<div id="form">
				{% csrf_token %}
				<p><textarea name="content" rows="5" cols="20">{{ post.content }}</textarea></p>
				<button id="update">更改</button>
				<button id="delete">删除</button>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col v2 right time">
			<p>{{ post.get_time }}</p>
		</div>
	</div>
	<div class="row">
		<div class="col v2">
			<h3>Comments</h3>
			{% for comment in post.comment_set.all %}
				<p>{{ comment.author }}：{{ comment.content }}</p>
			{% endfor %}
			<div id="comment" class="center" method="post">
				{% csrf_token %}
				<p>
					<label for="comment_nickname" class="form-l" for="author">昵称：</label>
					<input type="text" class="form-r" name="author" />
				</p>
				<p>
					<label for="comment_nickname" class="form-l" for="content">内容：</label>
					<input type="text" class="form-r" name="content" />
				</p>
				<p>
					<button type="submit" value="评论">评论</button>
				</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col v2 center">
			<div class="col {% if not previous %}disabled{% endif %}">
				<a href="{% url 'mblog:post' previous %}" class="link">上一篇</a>
			</div>
			<div class="col {% if not next %}disabled{% endif %}">
				<a href="{% url 'mblog:post' next %}" class="link">下一篇</a>
			</div>
		</div>
	</div>		
</div>
<script type="text/javascript" src="{% static "mblog/js/edit.min.js" %}"></script>
{% endblock %}